# Generated by Django 4.1 on 2022-09-03 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojavirtual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('categoria_name',)},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='categoria_name',
        ),
    ]
