# Generated by Django 4.1 on 2022-09-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojavirtual', '0002_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('category_name',)},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='price',
        ),
    ]
